{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "Fixes #29731\r\n\r\nThe `next()` call throws an exception if the default parameter is omitted and the iterator is exhausted.\r\nFix it by providing a default value.\r\n\r\nThe failure can be tested by commenting out lines 90 and 91 in the test (the `self.connect_nodes(2, 0)`). Since there is no connection, the node in question retrieves a single element in the 'getchaintips()' call. This scenario without the fix, aborts the test right away, throwing an `StopIteration` exception, and with the fix, the test properly waits until the timeout (`wait_until()` call).",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 2,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29753/comments",
   "created_at" : "2024-03-27T19:38:08Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29753/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/29753",
   "id" : 2211757164,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29753/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585q-eJX",
   "number" : 29753,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/29753.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29753",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/29753.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/29753"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29753/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29753/timeline",
   "title" : "test: fix StopIteration exception in p2p_node_network_limited.py",
   "updated_at" : "2024-03-27T19:48:19Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29753",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
      "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
      "followers_url" : "https://api.github.com/users/furszy/followers",
      "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
      "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/furszy",
      "id" : 5377650,
      "login" : "furszy",
      "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
      "organizations_url" : "https://api.github.com/users/furszy/orgs",
      "received_events_url" : "https://api.github.com/users/furszy/received_events",
      "repos_url" : "https://api.github.com/users/furszy/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/furszy"
   }
}
