{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "### Is there an existing issue for this?\r\n\r\n- [x] I have searched the existing issues\r\n\r\n### Current behaviour\r\n\r\nWhen I try to run: \r\n`test/functional/feature_rbf.py\r\nbash: test/functional/feature_rbf.py: No such file or directory\r\n`\r\nthis is what I get. This version of bitcoin-core was obtained from the Ubuntu software center.\r\n\r\n### Expected behaviour\r\n\r\nThe functional test runs and produces an output\r\n\r\n### Steps to reproduce\r\n\r\nRun the above functional test on bitcoin core obtained from the ubuntu software center\r\n\r\n### Relevant log output\r\n\r\n_No response_\r\n\r\n### How did you obtain Bitcoin Core\r\n\r\nPackage manager\r\n\r\n### What version of Bitcoin Core are you using?\r\n\r\n26.0\r\n\r\n### Operating system and version\r\n\r\nUbuntu 22.04 LTLS\r\n\r\n### Machine specifications\r\n\r\n_No response_",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 0,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29768/comments",
   "created_at" : "2024-03-30T14:15:09Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29768/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/29768",
   "id" : 2216480943,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29768/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "I_kwDOABII586EHNCv",
   "number" : 29768,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29768/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29768/timeline",
   "title" : "test: test/functional/feature_rbf.py fails to run on my machine",
   "updated_at" : "2024-03-30T14:36:51Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29768",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/20481828?v=4",
      "events_url" : "https://api.github.com/users/emc99/events{/privacy}",
      "followers_url" : "https://api.github.com/users/emc99/followers",
      "following_url" : "https://api.github.com/users/emc99/following{/other_user}",
      "gists_url" : "https://api.github.com/users/emc99/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/emc99",
      "id" : 20481828,
      "login" : "emc99",
      "node_id" : "MDQ6VXNlcjIwNDgxODI4",
      "organizations_url" : "https://api.github.com/users/emc99/orgs",
      "received_events_url" : "https://api.github.com/users/emc99/received_events",
      "repos_url" : "https://api.github.com/users/emc99/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/emc99/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/emc99/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/emc99"
   }
}
