{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "I am getting familiar with the `assume_utxo` tests and I found that the scenario of trying to activate a snapshot twice is not covered. This test is to ensure failure when loading a snapshot if there is already a snapshot-based chainstate.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 5,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29973/comments",
   "created_at" : "2024-04-26T13:34:47Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29973/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/29973",
   "id" : 2265804958,
   "labels" : [
      {
         "color" : "cccccc",
         "default" : false,
         "description" : "",
         "id" : 5334691551,
         "name" : "CI failed",
         "node_id" : "LA_kwDOABII588AAAABPfju3w",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29973/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585t2A2y",
   "number" : 29973,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/29973.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29973",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/29973.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/29973"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29973/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29973/timeline",
   "title" : "[Test] Assumeutxo: ensure failure when importing a snapshot twice",
   "updated_at" : "2024-04-26T13:55:43Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29973",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/19962151?v=4",
      "events_url" : "https://api.github.com/users/alfonsoromanz/events{/privacy}",
      "followers_url" : "https://api.github.com/users/alfonsoromanz/followers",
      "following_url" : "https://api.github.com/users/alfonsoromanz/following{/other_user}",
      "gists_url" : "https://api.github.com/users/alfonsoromanz/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/alfonsoromanz",
      "id" : 19962151,
      "login" : "alfonsoromanz",
      "node_id" : "MDQ6VXNlcjE5OTYyMTUx",
      "organizations_url" : "https://api.github.com/users/alfonsoromanz/orgs",
      "received_events_url" : "https://api.github.com/users/alfonsoromanz/received_events",
      "repos_url" : "https://api.github.com/users/alfonsoromanz/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/alfonsoromanz/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/alfonsoromanz/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/alfonsoromanz"
   }
}
